### ISSUE TITLE
Update Docs to Specify Version (or Range) for serverless

### ISSUE THREAD

**Issue by alexandermichels** [healthyregions/spatial-access#34]
When reproducing the steps to deploy the app, I ran into the following error while running "sls deploy":

```
✖ The Serverless version (4.1.12) does not satisfy the "frameworkVersion" (3) in serverless.yml
ServerlessError2: The Serverless version (4.1.12) does not satisfy the "frameworkVersion" (3) in serverless.yml
    at Service.loadServiceFileParam (file:///home/dijkstra/.serverless/releases/4.1.12/package/dist/sf-core.js:855:9321)
    at Service.load (file:///home/dijkstra/.serverless/releases/4.1.12/package/dist/sf-core.js:855:6963)
    at Serverless.init (file:///home/dijkstra/.serverless/releases/4.1.12/package/dist/sf-core.js:861:9726)
    at runFramework (file:///home/dijkstra/.serverless/releases/4.1.12/package/dist/sf-core.js:909:897)
    at async route (file:///home/dijkstra/.serverless/releases/4.1.12/package/dist/sf-core.js:920:16046)
    at async Object.run2 [as run] (file:///home/dijkstra/.serverless/releases/4.1.12/package/dist/sf-core.js:920:16444)
    at async run3 (file:///home/dijkstra/.serverless/releases/4.1.12/package/dist/sf-core.js:920:17704)
```

As the error implies, uninstalling serverless and installing a 3.* version solved the problem (in my case `npm install -g serverless@3.19.0`). I don't know enough about serverless to know if any 3.* works though.

**Comment by pengyin-shan** [comment]
@alexandermichels : my Serverless is on 3 as below:
<img width="455" alt="Screenshot 2024-07-11 at 1 39 27 PM" src="https://github.com/user-attachments/assets/4d3e0e0f-81a3-4671-a92a-706c8efa00a7">

And in `Serverless.yml`, we have 
```yaml
# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'
```
So far, version 3 works well. I think after I finish the last deployment, Serverless will probably upgrade its version. You can continue with version 3 since it has proven to work fine. We can consider upgrading the Serverless version in the future if needed.

**Comment by alexandermichels** [comment]
I'm not requesting an upgrade of the version, just asking to specify the version in Step 1 here: https://github.com/healthyregions/spatial-access?tab=readme-ov-file#deploy-backend-with-serverless to make the workflow easier to reproduce.

**Comment by pengyin-shan** [comment]
Oh I see, yes please go head with version 3 then
